defmodule Helpdesk.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:org_id, :uuid, null: false)
      add(:name, :text, null: false)
      add(:role, :text, null: false, default: "agent")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:tickets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:org_id, :uuid, null: false)
      add(:subject, :text, null: false)
      add(:status, :text, null: false, default: "open")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :assignee_id,
        references(:users,
          column: :id,
          name: "tickets_assignee_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:organisations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:users) do
      modify(
        :org_id,
        references(:organisations,
          column: :id,
          name: "users_org_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:organisations) do
      add(:name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:magma_workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:module, :text, null: false)
      add(:inputs, :binary)
      add(:actor, :binary)
      add(:tenant, :binary)
      add(:status, :text, null: false, default: "pending")
      add(:parent_workflow_id, :uuid)
      add(:parent_signal, :text)
      add(:result, :binary)
      add(:error, :binary)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:magma_waiters, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:name, :text, null: false)
      add(:kind, :text, null: false, default: "signal")
      add(:deadline, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workflow_id,
        references(:magma_workflows,
          column: :id,
          name: "magma_waiters_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:magma_waiters, [:workflow_id, :name], name: "magma_waiters_unique_wait_index")
    )

    create table(:magma_signals, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:name, :text, null: false)
      add(:payload, :binary)
      add(:consumed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workflow_id,
        references(:magma_workflows,
          column: :id,
          name: "magma_signals_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:magma_checkpoints, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:step_key, :binary, null: false)
      add(:step_label, :text, null: false)
      add(:output, :binary)
      add(:error, :binary)
      add(:undone_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workflow_id,
        references(:magma_workflows,
          column: :id,
          name: "magma_checkpoints_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:magma_checkpoints, [:workflow_id, :step_key],
        name: "magma_checkpoints_unique_step_index"
      )
    )

    create table(:grants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:org_id, :uuid, null: false)
      add(:permission, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "grants_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:grants, [:org_id, :user_id, :permission], name: "grants_one_per_user_index")
    )

    create table(:escalations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:org_id, :uuid, null: false)
      add(:reason, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :ticket_id,
        references(:tickets,
          column: :id,
          name: "escalations_ticket_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(
        :raised_by_id,
        references(:users,
          column: :id,
          name: "escalations_raised_by_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:audit_entries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:org_id, :uuid, null: false)
      add(:action, :text, null: false)
      add(:actor_name, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:audit_entries))

    drop(constraint(:escalations, "escalations_ticket_id_fkey"))

    drop(constraint(:escalations, "escalations_raised_by_id_fkey"))

    drop(table(:escalations))

    drop(constraint(:grants, "grants_user_id_fkey"))

    drop_if_exists(
      unique_index(:grants, [:org_id, :user_id, :permission], name: "grants_one_per_user_index")
    )

    drop(table(:grants))

    drop(constraint(:magma_checkpoints, "magma_checkpoints_workflow_id_fkey"))

    drop_if_exists(
      unique_index(:magma_checkpoints, [:workflow_id, :step_key],
        name: "magma_checkpoints_unique_step_index"
      )
    )

    drop(table(:magma_checkpoints))

    drop(constraint(:magma_signals, "magma_signals_workflow_id_fkey"))

    drop(table(:magma_signals))

    drop(constraint(:magma_waiters, "magma_waiters_workflow_id_fkey"))

    drop_if_exists(
      unique_index(:magma_waiters, [:workflow_id, :name], name: "magma_waiters_unique_wait_index")
    )

    drop(table(:magma_waiters))

    drop(table(:magma_workflows))

    alter table(:organisations) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:name)
    end

    drop(constraint(:users, "users_org_id_fkey"))

    alter table(:users) do
      modify(:org_id, :uuid)
    end

    drop(table(:organisations))

    drop(constraint(:tickets, "tickets_assignee_id_fkey"))

    drop(table(:tickets))

    drop(table(:users))
  end
end
