defmodule Helpdesk.Repo.Migrations.OneAttemptHoldsAWorkflow do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:magma_workflows) do
      add(:claimed_at, :utc_datetime_usec)
      add(:claimed_by, :bigint)
    end
  end

  def down do
    alter table(:magma_workflows) do
      remove(:claimed_by)
      remove(:claimed_at)
    end
  end
end
