defmodule Payouts.Repo.Migrations.MagmaStore do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:magma_workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:module, :text, null: false)
      add(:inputs, :binary)
      add(:actor, :binary)
      add(:tenant, :binary)
      add(:status, :text, null: false, default: "pending")
      add(:result, :binary)
      add(:error, :binary)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:magma_waiters, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:name, :text, null: false)
      add(:kind, :text, null: false, default: "signal")
      add(:deadline, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workflow_id,
        references(:magma_workflows,
          column: :id,
          name: "magma_waiters_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:magma_waiters, [:workflow_id, :name], name: "magma_waiters_unique_wait_index")
    )

    create table(:magma_signals, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:name, :text, null: false)
      add(:payload, :binary)
      add(:consumed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workflow_id,
        references(:magma_workflows,
          column: :id,
          name: "magma_signals_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:magma_checkpoints, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:step_key, :binary, null: false)
      add(:step_label, :text, null: false)
      add(:output, :binary)
      add(:error, :binary)
      add(:undone_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workflow_id,
        references(:magma_workflows,
          column: :id,
          name: "magma_checkpoints_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:magma_checkpoints, [:workflow_id, :step_key],
        name: "magma_checkpoints_unique_step_index"
      )
    )
  end

  def down do
    drop(constraint(:magma_checkpoints, "magma_checkpoints_workflow_id_fkey"))

    drop_if_exists(
      unique_index(:magma_checkpoints, [:workflow_id, :step_key],
        name: "magma_checkpoints_unique_step_index"
      )
    )

    drop(table(:magma_checkpoints))

    drop(constraint(:magma_signals, "magma_signals_workflow_id_fkey"))

    drop(table(:magma_signals))

    drop(constraint(:magma_waiters, "magma_waiters_workflow_id_fkey"))

    drop_if_exists(
      unique_index(:magma_waiters, [:workflow_id, :name], name: "magma_waiters_unique_wait_index")
    )

    drop(table(:magma_waiters))

    drop(table(:magma_workflows))
  end
end
