defmodule Payouts.Repo.Migrations.AddBeneficiaries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:beneficiaries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:destination_currency, :text, null: false)
      add(:account_number, :text, null: false)
      add(:bank_code, :text, null: false)
      add(:status, :text, null: false, default: "recorded")
      add(:provider_ref, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :customer_id,
        references(:customers,
          column: :id,
          name: "beneficiaries_customer_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:beneficiaries, [:customer_id, :destination_currency],
        name: "beneficiaries_one_per_rail_index"
      )
    )
  end

  def down do
    drop(constraint(:beneficiaries, "beneficiaries_customer_id_fkey"))

    drop_if_exists(
      unique_index(:beneficiaries, [:customer_id, :destination_currency],
        name: "beneficiaries_one_per_rail_index"
      )
    )

    drop(table(:beneficiaries))
  end
end
