defmodule Payouts.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transfers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:source_amount_cents, :bigint, null: false)
      add(:destination_currency, :text, null: false)
      add(:status, :text, null: false, default: "requested")
      add(:provider_reference, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:customer_id, :uuid, null: false)
    end

    create table(:ledger_entries, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:amount_cents, :bigint, null: false)
      add(:reason, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:customer_id, :uuid, null: false)
      add(:transfer_id, :uuid)
    end

    create table(:customers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:transfers) do
      modify(
        :customer_id,
        references(:customers,
          column: :id,
          name: "transfers_customer_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:ledger_entries) do
      modify(
        :customer_id,
        references(:customers,
          column: :id,
          name: "ledger_entries_customer_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :transfer_id,
        references(:transfers,
          column: :id,
          name: "ledger_entries_transfer_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:customers) do
      add(:name, :text, null: false)
      add(:balance_cents, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:customers) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:balance_cents)
      remove(:name)
    end

    drop(constraint(:ledger_entries, "ledger_entries_customer_id_fkey"))

    drop(constraint(:ledger_entries, "ledger_entries_transfer_id_fkey"))

    alter table(:ledger_entries) do
      modify(:transfer_id, :uuid)
      modify(:customer_id, :uuid)
    end

    drop(constraint(:transfers, "transfers_customer_id_fkey"))

    alter table(:transfers) do
      modify(:customer_id, :uuid)
    end

    drop(table(:customers))

    drop(table(:ledger_entries))

    drop(table(:transfers))
  end
end
