defmodule Payouts.Repo.Migrations.DropStoredBalance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers) do
      remove(:balance_cents)
    end
  end

  def down do
    alter table(:customers) do
      add(:balance_cents, :bigint, null: false, default: 0)
    end
  end
end
