defmodule Agency.Repo.Migrations.AddAttemptSaleMethod do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sale_attempts) do
      add(:sale_method, :text, null: false)
    end
  end

  def down do
    alter table(:sale_attempts) do
      remove(:sale_method)
    end
  end
end
