defmodule Agency.Repo.Migrations.AddExternalResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:title_searches, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:contract_id, :uuid, null: false)
      add(:status, :text, null: false, default: "ordered")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:title_searches, [:contract_id], name: "title_searches_unique_contract_index")
    )

    create table(:settlement_workspaces, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:contract_id, :uuid, null: false)
      add(:status, :text, null: false, default: "booked")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:settlement_workspaces, [:contract_id],
        name: "settlement_workspaces_unique_contract_index"
      )
    )

    create table(:finance_applications, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:contract_id, :uuid, null: false)
      add(:status, :text, null: false, default: "assessing")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:finance_applications, [:contract_id],
        name: "finance_applications_unique_contract_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:finance_applications, [:contract_id],
        name: "finance_applications_unique_contract_index"
      )
    )

    drop(table(:finance_applications))

    drop_if_exists(
      unique_index(:settlement_workspaces, [:contract_id],
        name: "settlement_workspaces_unique_contract_index"
      )
    )

    drop(table(:settlement_workspaces))

    drop_if_exists(
      unique_index(:title_searches, [:contract_id], name: "title_searches_unique_contract_index")
    )

    drop(table(:title_searches))
  end
end
