defmodule Agency.Repo.Migrations.AddSaleResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sale_attempts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:generation, :bigint, null: false)
      add(:outcome, :text, null: false, default: "running")
      add(:opened_at, :utc_datetime, null: false)
      add(:closed_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:agency_agreement_id, :uuid, null: false)
      add(:predecessor_id, :uuid)
    end

    create table(:properties, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:address, :text, null: false)
      add(:suburb, :text, null: false)
      add(:jurisdiction, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:offers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:amount, :bigint, null: false)
      add(:requested_conditions, {:array, :text}, null: false, default: [])
      add(:expires_at, :utc_datetime, null: false)
      add(:status, :text, null: false, default: "live")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :sale_attempt_id,
        references(:sale_attempts,
          column: :id,
          name: "offers_sale_attempt_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:buyer_id, :uuid, null: false)
      add(:supersedes_id, :uuid)
    end

    create table(:deposits, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:amount, :bigint, null: false)
      add(:held_in, :text, null: false)
      add(:status, :text, null: false, default: "held")
      add(:forfeited_to, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:contract_id, :uuid, null: false)
    end

    create table(:contracts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:deposits) do
      modify(
        :contract_id,
        references(:contracts,
          column: :id,
          name: "deposits_contract_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:contracts) do
      add(:price, :bigint, null: false)
      add(:exchanged_at, :utc_datetime, null: false)
      add(:unconditional_at, :utc_datetime)
      add(:settlement_date, :date, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :sale_attempt_id,
        references(:sale_attempts,
          column: :id,
          name: "contracts_sale_attempt_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:buyer_id, :uuid, null: false)
    end

    create table(:conditions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:kind, :text, null: false)
      add(:due_date, :date, null: false)
      add(:status, :text, null: false, default: "pending")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :contract_id,
        references(:contracts,
          column: :id,
          name: "conditions_contract_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:compliance_documents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:kind, :text, null: false)
      add(:received_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:agency_agreement_id, :uuid, null: false)
    end

    create table(:commissions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:amount, :bigint, null: false)
      add(:accrued_at, :utc_datetime, null: false)
      add(:payable_on, :text, null: false)
      add(:disbursed_at, :utc_datetime)
      add(:paid_from, :text)
      add(:outcome, :text, null: false, default: "accrued")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :sale_attempt_id,
        references(:sale_attempts,
          column: :id,
          name: "commissions_sale_attempt_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create table(:buyers, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:offers) do
      modify(
        :buyer_id,
        references(:buyers,
          column: :id,
          name: "offers_buyer_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :supersedes_id,
        references(:offers,
          column: :id,
          name: "offers_supersedes_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:contracts) do
      modify(
        :buyer_id,
        references(:buyers,
          column: :id,
          name: "contracts_buyer_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:buyers) do
      add(:name, :text, null: false)
      add(:conveyancer, :text)
      add(:lender, :text)
      add(:register_status, :text, null: false, default: "available")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:agency_agreement_id, :uuid, null: false)
    end

    create table(:agency_agreements, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
    end

    alter table(:sale_attempts) do
      modify(
        :agency_agreement_id,
        references(:agency_agreements,
          column: :id,
          name: "sale_attempts_agency_agreement_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :predecessor_id,
        references(:sale_attempts,
          column: :id,
          name: "sale_attempts_predecessor_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:compliance_documents) do
      modify(
        :agency_agreement_id,
        references(:agency_agreements,
          column: :id,
          name: "compliance_documents_agency_agreement_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:buyers) do
      modify(
        :agency_agreement_id,
        references(:agency_agreements,
          column: :id,
          name: "buyers_agency_agreement_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:agency_agreements) do
      add(:vendor_name, :text, null: false)
      add(:agent_name, :text, null: false)
      add(:appointment, :text, null: false)
      add(:term_start, :date, null: false)
      add(:term_end, :date, null: false)
      add(:commission_rate, :decimal, null: false)
      add(:commission_trigger, :text, null: false)
      add(:sale_method, :text, null: false)
      add(:guide_price, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :property_id,
        references(:properties,
          column: :id,
          name: "agency_agreements_property_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end
  end

  def down do
    drop(constraint(:agency_agreements, "agency_agreements_property_id_fkey"))

    alter table(:agency_agreements) do
      remove(:property_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:guide_price)
      remove(:sale_method)
      remove(:commission_trigger)
      remove(:commission_rate)
      remove(:term_end)
      remove(:term_start)
      remove(:appointment)
      remove(:agent_name)
      remove(:vendor_name)
    end

    drop(constraint(:buyers, "buyers_agency_agreement_id_fkey"))

    alter table(:buyers) do
      modify(:agency_agreement_id, :uuid)
    end

    drop(constraint(:compliance_documents, "compliance_documents_agency_agreement_id_fkey"))

    alter table(:compliance_documents) do
      modify(:agency_agreement_id, :uuid)
    end

    drop(constraint(:sale_attempts, "sale_attempts_agency_agreement_id_fkey"))

    drop(constraint(:sale_attempts, "sale_attempts_predecessor_id_fkey"))

    alter table(:sale_attempts) do
      modify(:predecessor_id, :uuid)
      modify(:agency_agreement_id, :uuid)
    end

    drop(table(:agency_agreements))

    alter table(:buyers) do
      remove(:agency_agreement_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:register_status)
      remove(:lender)
      remove(:conveyancer)
      remove(:name)
    end

    drop(constraint(:contracts, "contracts_buyer_id_fkey"))

    alter table(:contracts) do
      modify(:buyer_id, :uuid)
    end

    drop(constraint(:offers, "offers_buyer_id_fkey"))

    drop(constraint(:offers, "offers_supersedes_id_fkey"))

    alter table(:offers) do
      modify(:supersedes_id, :uuid)
      modify(:buyer_id, :uuid)
    end

    drop(table(:buyers))

    drop(constraint(:commissions, "commissions_sale_attempt_id_fkey"))

    drop(table(:commissions))

    drop(table(:compliance_documents))

    drop(constraint(:conditions, "conditions_contract_id_fkey"))

    drop(table(:conditions))

    drop(constraint(:contracts, "contracts_sale_attempt_id_fkey"))

    alter table(:contracts) do
      remove(:buyer_id)
      remove(:sale_attempt_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:settlement_date)
      remove(:unconditional_at)
      remove(:exchanged_at)
      remove(:price)
    end

    drop(constraint(:deposits, "deposits_contract_id_fkey"))

    alter table(:deposits) do
      modify(:contract_id, :uuid)
    end

    drop(table(:contracts))

    drop(table(:deposits))

    drop(constraint(:offers, "offers_sale_attempt_id_fkey"))

    drop(table(:offers))

    drop(table(:properties))

    drop(table(:sale_attempts))
  end
end
