defmodule Magma.TestRepo.Migrations.AddMagmaWorkflows do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:magma_workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:module, :text, null: false)
      add(:inputs, :binary)
      add(:actor, :binary)
      add(:tenant, :binary)
      add(:status, :text, null: false, default: "pending")
      add(:result, :binary)
      add(:error, :binary)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:magma_workflows))
  end
end
