defmodule Magma.TestRepo.Migrations.WaitersRecordWhatTheyWaitFor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:magma_waiters) do
      add(:kind, :text, null: false, default: "signal")
    end
  end

  def down do
    alter table(:magma_waiters) do
      remove(:kind)
    end
  end
end
