defmodule Magma.TestRepo.Migrations.WorkflowsRecordTheirParent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:magma_workflows) do
      add(:parent_workflow_id, :uuid)
      add(:parent_signal, :text)
    end
  end

  def down do
    alter table(:magma_workflows) do
      remove(:parent_signal)
      remove(:parent_workflow_id)
    end
  end
end
